[package]
name = "projectM-SDL"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
sdl2 = "0.35.2"
projectm-rs = "^1.0.3"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
